import './globals.css'
import type { Metadata } from 'next'
import { Inter, Space_Mono } from 'next/font/google'
import Navbar from './Navbar'
import Footer from './Footer'

const space_mono = Space_Mono({weight: ['400','700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={ space_mono.className}>
      <div className='w-10/12 mx-auto mt-5 pt-4'><Navbar /> </div>
      {children}
      <Footer />
      </body>
    </html>
  )
}
